default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: navrails_development
test:
  <<: *default
  database: navrails_test
production:
  <<: *default
  database: navrails_production
  username: navrails
  password: <%= ENV['NAVRAILS_DATABASE_PASSWORD'] %>
